xname: Lightgates
description: Lightgates application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable:
  flutter_bloc:
  http:
  page_indicator:
  animator:
  url_launcher:
  country_code_picker:
  shared_preferences:
  pull_to_refresh:
  flutter_svg: ^0.19.0
  image_cropper:
  image_picker: ^0.6.7+11
  multi_image_picker:
  photo_view:
  flutter_html: 0.11.1 #preferred version 0.11.1
  intl:
  table_calendar:
  youtube_player_flutter:
  file_picker: 1.9.0
  flutter_image_compress: ^0.7.0
  share:
  firebase_messaging: ^7.0.0
  flutter_launcher_icons:
  fluttertoast:
  pin_code_fields:
  emoji_picker: ^0.1.0
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18
  video_player: ^0.11.0
  permission_handler: ^5.0.1+1
  flutter_speed_dial: 1.2.5
  webview_flutter: ^0.3.24
  flutter_app_badger: ^1.1.2
  reorderables: ^0.3.2
  # video_trimmer: ^0.2.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"

# The following section is specific to Flutter.
name: 'school_pal'
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
      - lib/assets/images/logo.png
      - lib/assets/images/home_screen_background.jpg
      - lib/assets/images/school_board.png
      - lib/assets/images/school_kids.png
      - lib/assets/images/school_bird.png
      - lib/assets/images/avatar.png
      - lib/assets/images/teachers.svg
      - lib/assets/images/class_categories.svg
      - lib/assets/images/classes.svg
      - lib/assets/images/labels.svg
      - lib/assets/images/levels.svg
      - lib/assets/images/students.svg
      - lib/assets/images/subjects.svg
      - lib/assets/images/network_error.svg
      - lib/assets/images/no_data.svg
      - lib/assets/images/payment.svg
      - lib/assets/images/assessment1.svg
      - lib/assets/images/assessment2.svg
      - lib/assets/images/assessment3.svg
      - lib/assets/images/schedule1.svg
      - lib/assets/images/schedule2.svg
      - lib/assets/images/schedule3.svg
      - lib/assets/images/verified.svg
      - lib/assets/images/contact_alert.svg
      - lib/assets/images/contact_developer.svg
      - lib/assets/images/contact.svg
      - lib/assets/images/welcome.svg
      - lib/assets/images/learning1.svg
      - lib/assets/images/learning2.svg
      - lib/assets/images/learning3.svg
      - lib/assets/images/news.svg
      - lib/assets/images/result1.svg
      - lib/assets/images/result2.svg
      - lib/assets/images/bus_tracker.svg
      - lib/assets/images/data_storage.svg
      - lib/assets/images/invoice.svg
      - lib/assets/images/notification.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CenturyGothic
      fonts:
        - asset: lib/assets/fonts/gothic.ttf
